# Generated by Django 5.0.6 on 2024-07-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampledocker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Number',
            new_name='Number_user',
        ),
    ]
