# Generated by Django 5.0.6 on 2024-07-16 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampledocker', '0002_rename_number_number_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='number_user',
            name='user_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sampledocker.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=10),
        ),
    ]
