# Generated by Django 5.0.6 on 2024-07-16 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampledocker', '0003_number_user_user_id_alter_user_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number_user',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='number_user', to='sampledocker.user'),
        ),
    ]
